/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dtu.project.gui;

import dtu.project.entities.Activity;
import dtu.project.exceptions.DuplicateActivityName;
import dtu.project.exceptions.DuplicateProjectName;
import dtu.project.exceptions.DuplicateUser;
import java.time.format.DateTimeParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.PatternSyntaxException;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Jonathan
 */
public class ActivityPanel extends PanelTemplate {

    /**
     * Creates new form ActivityPanel
     */
    public ActivityPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectProjectLabel1 = new javax.swing.JLabel();
        projectListComboBox1 = new javax.swing.JComboBox<>();
        activityNameLabel1 = new javax.swing.JLabel();
        activityNameTextField1 = new javax.swing.JTextField();
        activityUserLabel1 = new javax.swing.JLabel();
        estimatedHoursLabel1 = new javax.swing.JLabel();
        activityStartDateLabel1 = new javax.swing.JLabel();
        activityEndDateLabel1 = new javax.swing.JLabel();
        activityUserComboBox1 = new javax.swing.JComboBox<>();
        estimatedHoursTextField1 = new javax.swing.JTextField();
        activityStartDateTextField1 = new javax.swing.JTextField();
        activityEndDateTextField1 = new javax.swing.JTextField();
        addActivityButton = new javax.swing.JButton();
        editActivityButton = new javax.swing.JButton();
        activitySelectLabel1 = new javax.swing.JLabel();
        activitySelectComboBox1 = new javax.swing.JComboBox<>();
        removeActivityButton = new javax.swing.JButton();
        addUserComboBox = new javax.swing.JComboBox<>();
        addUserButton = new javax.swing.JButton();

        selectProjectLabel1.setText("Select Project");

        projectListComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        activityNameLabel1.setText("Activity Name");

        activityNameTextField1.setText("Activity Name");

        activityUserLabel1.setText("Activity Leader/Responsible");

        estimatedHoursLabel1.setText("Estimated Hours");

        activityStartDateLabel1.setText("Start Date");

        activityEndDateLabel1.setText("End Date");

        activityUserComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        estimatedHoursTextField1.setText("45");

        activityStartDateTextField1.setText("2019-05-05 13:12");

        activityEndDateTextField1.setText("2019-05-05 13:13");

        addActivityButton.setText("Add Activity");
        addActivityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActivityButtonActionPerformed(evt);
            }
        });

        editActivityButton.setText("Edit Activity");
        editActivityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActivityButtonActionPerformed(evt);
            }
        });

        activitySelectLabel1.setText("Select Activity");

        activitySelectComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        removeActivityButton.setText("Remove Activity");
        removeActivityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActivityButtonActionPerformed(evt);
            }
        });

        addUserComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        addUserButton.setText("Add User To Selected Activity");
        addUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(activitySelectLabel1)
                                .addComponent(activitySelectComboBox1, 0, 700, Short.MAX_VALUE)
                                .addComponent(projectListComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(activityNameTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(activityNameLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(activityUserComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(activityUserLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(estimatedHoursTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(estimatedHoursLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(activityStartDateTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(activityStartDateLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(activityEndDateLabel1)
                                    .addComponent(activityEndDateTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addActivityButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editActivityButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeActivityButton)))
                        .addContainerGap(71, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectProjectLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addUserComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(addUserButton)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectProjectLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(projectListComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(activitySelectLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(activitySelectComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(activityNameLabel1)
                    .addComponent(activityUserLabel1)
                    .addComponent(estimatedHoursLabel1)
                    .addComponent(activityStartDateLabel1)
                    .addComponent(activityEndDateLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(activityNameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(activityUserComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(estimatedHoursTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(activityStartDateTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(activityEndDateTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addActivityButton)
                    .addComponent(editActivityButton)
                    .addComponent(removeActivityButton))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addUserComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addUserButton))
                .addContainerGap(234, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addActivityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActivityButtonActionPerformed
        try {
            PG.addActivityButton(projectListComboBox1, 
                    activityNameTextField1, 
                    estimatedHoursTextField1, 
                    activityStartDateTextField1, 
                    activityEndDateTextField1, 
                    activityUserComboBox1);
        } catch (DuplicateActivityName | NumberFormatException | DateTimeParseException | PatternSyntaxException e) {
            System.err.println(e);
        }

        MF.updateAll();
    }//GEN-LAST:event_addActivityButtonActionPerformed

    private void editActivityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActivityButtonActionPerformed
        try {
            PG.editActivity(projectListComboBox1, activitySelectComboBox1, activityNameTextField1, estimatedHoursTextField1, activityStartDateTextField1, activityEndDateTextField1, activityUserComboBox1);
        } catch (DuplicateActivityName e) {
            System.err.println(e);
        }
        MF.updateAll();
    }//GEN-LAST:event_editActivityButtonActionPerformed

    private void removeActivityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActivityButtonActionPerformed
        PG.removeActivity(projectListComboBox1, activitySelectComboBox1);
        MF.updateAll();
    }//GEN-LAST:event_removeActivityButtonActionPerformed

    private void addUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserButtonActionPerformed
        try {
            PG.addUserToActivity(PG.getActivity(PG.getProject(projectListComboBox1.getSelectedIndex()), activitySelectComboBox1.getSelectedIndex()), PG.getUser(addUserComboBox.getSelectedIndex()));
            MF.updateAll();
        } catch (DuplicateUser e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_addUserButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel activityEndDateLabel1;
    private javax.swing.JTextField activityEndDateTextField1;
    private javax.swing.JLabel activityNameLabel1;
    private javax.swing.JTextField activityNameTextField1;
    private javax.swing.JComboBox<String> activitySelectComboBox1;
    private javax.swing.JLabel activitySelectLabel1;
    private javax.swing.JLabel activityStartDateLabel1;
    private javax.swing.JTextField activityStartDateTextField1;
    private javax.swing.JComboBox<String> activityUserComboBox1;
    private javax.swing.JLabel activityUserLabel1;
    private javax.swing.JButton addActivityButton;
    private javax.swing.JButton addUserButton;
    private javax.swing.JComboBox<String> addUserComboBox;
    private javax.swing.JButton editActivityButton;
    private javax.swing.JLabel estimatedHoursLabel1;
    private javax.swing.JTextField estimatedHoursTextField1;
    private javax.swing.JComboBox<String> projectListComboBox1;
    private javax.swing.JButton removeActivityButton;
    private javax.swing.JLabel selectProjectLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void initFields() {
        activityUserComboBox1.setModel(PG.getUserDefaultComboBoxModel());
        addUserComboBox.setModel(PG.getUserDefaultComboBoxModel());
        if (PG.isProjectListEmpty()) {
            projectListComboBox1.setModel(new DefaultComboBoxModel<>(new String[]{"empty"}));
            activitySelectComboBox1.setModel(new DefaultComboBoxModel<>(new String[]{"empty"}));
            addActivityButton.setEnabled(false);
            editActivityButton.setEnabled(false);
            removeActivityButton.setEnabled(false);
            addUserButton.setEnabled(false);
        } else if (PG.isActivityListEmpty(PG.getProject(projectListComboBox1.getSelectedIndex()))) {
            addActivityButton.setEnabled(true);
            editActivityButton.setEnabled(false);
            removeActivityButton.setEnabled(false);
            addUserButton.setEnabled(false);
            projectListComboBox1.setModel(PG.getProjectDefaultComboBoxModel());
            activitySelectComboBox1.setModel(new DefaultComboBoxModel<>(new String[]{"empty"}));
        } else {
            addActivityButton.setEnabled(true);
            editActivityButton.setEnabled(true);
            removeActivityButton.setEnabled(true);
            addUserButton.setEnabled(true);
            projectListComboBox1.setModel(PG.getProjectDefaultComboBoxModel());
            activitySelectComboBox1.setModel(PG.getActivitytDefaultComboBoxModel(PG.getProject(projectListComboBox1.getSelectedIndex())));

        }

    }
}
