/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dtu.project.gui;

import dtu.project.app.Plan;
import dtu.project.app.ProjectApp;
import dtu.project.app.User;
import java.util.List;

/**
 *
 * @author Jonathan
 */
public class MainFrame extends javax.swing.JFrame {

    private final ProjectApp PA;
    private final MainFrame MF;

    public User getCurrentUser() {
        return PA.getCurrentUser();
    }

    public void setCurrentUser(User currentUser) {
        PA.setCurrentUser(currentUser);
    }

    public List<User> getUsers() {
        return PA.getUsers();
    }

    public void setUsers(List<User> users) {
        PA.setUsers(users);
    }

    public List<Plan> getPlans() {
        return PA.getPlans();
    }

    public void setPlans(List<Plan> plans) {
        PA.setPlans(plans);
    }

    public <E> boolean add(E element, List<E> list) {
        return PA.add(element, list);
    }

    public <E> List<E> search(E element, List<E> list, String searchText) {
        return PA.search(element, list, searchText);
    }

    public void login(String username, String passsword) {
        PA.login(username, passsword);
    }

    /**
     * Creates new form MainFrame
     */
    private MainFrame() {
        PA = new ProjectApp();
        MF = this;
        initComponents();
        this.loginPanel1.setup(MF);
        this.homePanel1.setup(MF);
        this.adminPanel1.setup(MF);
        this.jTabbedPane1.setEnabledAt(1, false);
        this.jTabbedPane1.setEnabledAt(2, false);
    }
    
    public void updateAll() {
        this.loginPanel1.update();
        this.homePanel1.update();
        this.adminPanel1.update();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        loginPanel1 = new dtu.project.gui.LoginPanel();
        homePanel1 = new dtu.project.gui.HomePanel();
        adminPanel1 = new dtu.project.gui.AdminPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addTab("Login Panel", loginPanel1);
        jTabbedPane1.addTab("Home Panel", homePanel1);
        jTabbedPane1.addTab("Admin Panel", adminPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private dtu.project.gui.AdminPanel adminPanel1;
    private dtu.project.gui.HomePanel homePanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private dtu.project.gui.LoginPanel loginPanel1;
    // End of variables declaration//GEN-END:variables
}
