/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dtu.project.gui;

import dtu.project.entities.Project;
import dtu.project.entities.TimePeriod;
import dtu.project.enums.ProjectType;
import dtu.project.exceptions.DuplicateProjectName;
import java.time.format.DateTimeParseException;
import java.util.regex.PatternSyntaxException;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Jonathan
 */
public class ProjectPanel extends PanelTemplate {

    /**
     * Creates new form ProjectPanel
     */
    public ProjectPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        projectNameLabel1 = new javax.swing.JLabel();
        projectNameTextField1 = new javax.swing.JTextField();
        projectTypeLabel1 = new javax.swing.JLabel();
        projectTypeComboBox1 = new javax.swing.JComboBox<>();
        projectTimePeriodUndefinedCheckBox1 = new javax.swing.JCheckBox();
        projectStartDateLabel1 = new javax.swing.JLabel();
        projectEndDateLabel1 = new javax.swing.JLabel();
        projectStartDateTextField1 = new javax.swing.JTextField();
        projectEndDateTextField1 = new javax.swing.JTextField();
        addProjectButton = new javax.swing.JButton();
        projectSelectComboBox1 = new javax.swing.JComboBox<>();
        projectSelectLabel1 = new javax.swing.JLabel();
        editProjectButton = new javax.swing.JButton();
        removeProjectButton = new javax.swing.JButton();
        projectManagerLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        projectManagerList = new javax.swing.JList<>();

        projectNameLabel1.setText("Project Name");

        projectNameTextField1.setText("BankingSystem3");

        projectTypeLabel1.setText("Project Type");

        projectTypeComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        projectTimePeriodUndefinedCheckBox1.setText("Timeperiod Undefined");

        projectStartDateLabel1.setText("Project Start Date");

        projectEndDateLabel1.setText("Project End Date");

        projectStartDateTextField1.setText("2019-05-05 13:12");

        projectEndDateTextField1.setText("2019-05-05 13:13");

        addProjectButton.setText("Add Project");
        addProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProjectButtonActionPerformed(evt);
            }
        });

        projectSelectComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        projectSelectLabel1.setText("Select Project");

        editProjectButton.setText("Edit Project");
        editProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProjectButtonActionPerformed(evt);
            }
        });

        removeProjectButton.setText("Remove Project");
        removeProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeProjectButtonActionPerformed(evt);
            }
        });

        projectManagerLabel1.setText("Project Manager");

        projectManagerList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(projectManagerList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(projectSelectLabel1)
                            .addComponent(projectSelectComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(projectNameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(projectNameLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(projectTypeComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(projectTypeLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addProjectButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editProjectButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(removeProjectButton)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(projectManagerLabel1)
                                .addGap(0, 52, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(projectStartDateTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(projectStartDateLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(projectEndDateLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(projectEndDateTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(projectTimePeriodUndefinedCheckBox1)))
                        .addGap(68, 68, 68))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(projectSelectLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(projectSelectComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(projectNameLabel1)
                    .addComponent(projectTypeLabel1)
                    .addComponent(projectStartDateLabel1)
                    .addComponent(projectEndDateLabel1)
                    .addComponent(projectManagerLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(projectNameTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(projectTypeComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(projectStartDateTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(projectEndDateTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(projectTimePeriodUndefinedCheckBox1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addProjectButton)
                            .addComponent(editProjectButton)
                            .addComponent(removeProjectButton)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(228, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProjectButtonActionPerformed
        try {
            Project p = new Project.Builder()
                    .setProjectName(projectNameTextField1.getText())
                    .setProjectType(ProjectType.valueOf(projectTypeComboBox1.getItemAt(projectTypeComboBox1.getSelectedIndex())))
                    .build();
            if (projectTimePeriodUndefinedCheckBox1.isSelected()) {
                p.setTimePeriod(new TimePeriod(projectStartDateTextField1.getText(), projectEndDateTextField1.getText()));
            }
            if (!projectManagerList.isSelectionEmpty()) {
                p.setProjectManager(PG.getUser(projectManagerList.getSelectedIndex()));
            }
            PG.addProject(p);

        } catch (DuplicateProjectName | DateTimeParseException | PatternSyntaxException | ArrayIndexOutOfBoundsException e) {
            System.err.println(e);
        }

        MF.updateAll();
    }//GEN-LAST:event_addProjectButtonActionPerformed

    private void editProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProjectButtonActionPerformed
        try {
            PG.setProject(projectSelectComboBox1.getSelectedIndex(), new Project.Builder()
                    .setProjectName(projectNameTextField1.getText())
                    .setProjectType(ProjectType.valueOf(projectTypeComboBox1.getItemAt(projectTypeComboBox1.getSelectedIndex())))
                    .build());
            if (projectTimePeriodUndefinedCheckBox1.isSelected()) {
                PG.getProject(projectSelectComboBox1.getSelectedIndex()).setTimePeriod(new TimePeriod(projectStartDateTextField1.getText(), projectEndDateTextField1.getText()));
            }
            if (!projectManagerList.isSelectionEmpty()) {
                PG.getProject(projectSelectComboBox1.getSelectedIndex()).setProjectManager(PG.getUser(projectManagerList.getSelectedIndex()));
            }

        } catch (ArrayIndexOutOfBoundsException | DateTimeParseException | PatternSyntaxException e) {
            System.err.println(e);
        }
        MF.updateAll();
    }//GEN-LAST:event_editProjectButtonActionPerformed

    private void removeProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeProjectButtonActionPerformed
        PG.removeProject(PG.getProject(projectSelectComboBox1.getSelectedIndex()));
        MF.updateAll();
    }//GEN-LAST:event_removeProjectButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProjectButton;
    private javax.swing.JButton editProjectButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel projectEndDateLabel1;
    private javax.swing.JTextField projectEndDateTextField1;
    private javax.swing.JLabel projectManagerLabel1;
    private javax.swing.JList<String> projectManagerList;
    private javax.swing.JLabel projectNameLabel1;
    private javax.swing.JTextField projectNameTextField1;
    private javax.swing.JComboBox<String> projectSelectComboBox1;
    private javax.swing.JLabel projectSelectLabel1;
    private javax.swing.JLabel projectStartDateLabel1;
    private javax.swing.JTextField projectStartDateTextField1;
    private javax.swing.JCheckBox projectTimePeriodUndefinedCheckBox1;
    private javax.swing.JComboBox<String> projectTypeComboBox1;
    private javax.swing.JLabel projectTypeLabel1;
    private javax.swing.JButton removeProjectButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void initFields() {
        projectManagerList.setModel(PG.getUserDefaultListModel());
        this.projectTypeComboBox1.setModel(new DefaultComboBoxModel<>(new String[]{ProjectType.INTERNAL.toString(), ProjectType.EXTERNAL.toString()}));
        if (PG.isProjectListEmpty()) {
            this.projectSelectComboBox1.setModel(new DefaultComboBoxModel<>(new String[]{"empty"}));
            this.editProjectButton.setEnabled(false);
            this.removeProjectButton.setEnabled(false);
        } else {
            this.projectSelectComboBox1.setModel(PG.getProjectDefaultComboBoxModel());
            this.editProjectButton.setEnabled(true);
            this.removeProjectButton.setEnabled(true);
        }
    }
}
